function render(){
 const list=filtered(),active=activeTasks(),view=els.view?.value||'active';
 $('#mTotal').textContent=active.length;$('#mReceive').textContent=active.filter(t=>t.direction==='인수').length;$('#mHandover').textContent=active.filter(t=>t.direction==='인계').length;$('#mSoon').textContent=active.filter(isSoon).length;$('#mImportant').textContent=active.filter(t=>t.priority==='높음').length;
 els.body.innerHTML=list.map(t=>{const due=dueLabel(t),cs=checklistStats(t),rowClass=view==='archive'?'archived-row':view==='trash'?'trash-row':'';return `<tr class="${rowClass}"><td class="title-cell"><div class="task-title">${esc(t.title)}</div><div class="task-sub">${esc([t.category,t.counterpart].filter(Boolean).join(' · ')||t.content||'업무내용 없음')}</div>${cs.total?`<div class="check-summary"><div class="check-mini"><span style="width:${cs.pct}%"></span></div><span>체크 ${cs.done}/${cs.total}</span></div>`:''}${view==='archive'?'<div class="view-note">보관된 업무</div>':view==='trash'?'<div class="view-note">30일 후 자동 완전삭제</div>':''}</td><td><span class="badge ${t.direction==='인수'?'receive':'handover'}">${t.direction}</span></td><td class="${due?'due-soon':''}">${esc(t.dueDate)}${due?`<span class="due-chip">${esc(due)}</span>`:''}</td><td>${view==='trash'?esc(t.status):`<select class="control status-select" data-status="${t.id}" aria-label="${esc(t.title)} 진행상태">${statusOptions(t)}</select>`}</td><td><span class="badge ${t.priority==='높음'?'high':t.priority==='보통'?'medium':'low'}">${t.priority}</span></td><td><div class="progress"><div class="bar"><span style="width:${t.progress}%"></span></div><span class="pct">${t.progress}%</span></div></td><td>${esc(t.notes||'-')}</td><td><div class="actions">${actionButtons(t,view)}</div></td></tr>`}).join('');
 els.mobile.innerHTML=list.map(t=>{const due=dueLabel(t),cs=checklistStats(t);return `<article class="mobile-card ${view==='trash'?'trash-row':''}"><div class="top"><div><span class="badge ${t.direction==='인수'?'receive':'handover'}">${t.direction}</span> <span class="badge ${t.priority==='높음'?'high':t.priority==='보통'?'medium':'low'}">${t.priority}</span></div>${view==='trash'?`<span class="status">${esc(t.status)}</span>`:`<select class="control status-select" data-status="${t.id}">${statusOptions(t)}</select>`}</div><h3>${esc(t.title)}</h3><p>${esc(t.content||'업무내용 없음')}</p>${cs.total?`<div class="check-summary"><div class="check-mini"><span style="width:${cs.pct}%"></span></div><span>체크 ${cs.done}/${cs.total}</span></div>`:''}<div class="meta"><div><b>처리기한</b><span class="${due?'due-soon':''}">${esc(t.dueDate)} ${due?`· ${esc(due)}`:''}</span></div><div><b>완료율</b>${t.progress}%</div></div><div class="card-actions">${actionButtons(t,view)}</div></article>`}).join('');
 els.empty.style.display=list.length?'none':'block';els.mobile.style.display=list.length?'':'none';const viewName=view==='archive'?'보관함':view==='trash'?'휴지통':'관리 중';els.count.textContent=`${viewName} · ${list.length}개 업무 표시 중 · 관리 중 전체 ${active.length}개`;save();
}
function openModal(task){const t=task||{id:'',title:'',direction:'인수',category:'',counterpart:'',departmentRole:'',contact:'',dueDate:localDate(7),status:'예정',priority:'보통',progress:0,content:'',checklist:'',documents:'',notes:''};$('#modalTitle').textContent=task?'업무 수정':'업무 등록';els.id.value=t.id;els.title.value=t.title;els.dir.value=t.direction;els.category.value=t.category||'';els.counterpart.value=t.counterpart||'';els.departmentRole.value=t.departmentRole||'';els.contact.value=t.contact||'';els.due.value=t.dueDate;els.fstatus.value=t.status;els.fpriority.value=t.priority;els.progress.value=t.progress;els.progressValue.textContent=t.progress+'%';els.content.value=t.content||'';els.checklist.value=t.checklist||'';els.documents.value=t.documents||'';els.notes.value=t.notes||'';els.modal.classList.add('open');setTimeout(()=>els.title.focus(),30)}
function closeModal(){els.modal.classList.remove('open');els.form.reset()}
function toast(msg,type='success',ms=3200,action=null){const el=document.createElement('div');el.className=`toast ${type}`;const row=document.createElement('div');row.className='toast-row';const span=document.createElement('span');span.textContent=msg;row.appendChild(span);if(action){const b=document.createElement('button');b.className='toast-action';b.textContent=action.label;b.addEventListener('click',()=>{action.run();el.remove()});row.appendChild(b)}el.appendChild(row);$('#toastWrap').appendChild(el);setTimeout(()=>el.remove(),ms)}
function setTaskStatus(id,status){const t=tasks.find(x=>x.id===id);if(!t||t.deletedAt)return;if(status==='완료'&&t.status!=='완료'){t.previousProgress=t.progress;t.progress=100}else if(t.status==='완료'&&status!=='완료'){t.progress=Math.max(0,Math.min(100,Number(t.previousProgress)|| (status==='진행중'?50:0)))}t.status=status;t.updatedAt=Date.now();save();render();toast(`진행상태를 “${status}”로 변경했습니다.`)}
function deleteTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;if(!confirm(`“${t.title}” 업무를 휴지통으로 이동할까요?`))return;const prev={deletedAt:t.deletedAt,archivedAt:t.archivedAt};t.deletedAt=Date.now();t.archivedAt=null;t.updatedAt=Date.now();save();render();toast('업무를 휴지통으로 이동했습니다.','success',6000,{label:'실행 취소',run:()=>{t.deletedAt=prev.deletedAt||null;t.archivedAt=prev.archivedAt||null;t.updatedAt=Date.now();save();render();toast('삭제를 취소했습니다.')}})}
function archiveTask(id){const t=tasks.find(x=>x.id===id);if(!t||t.deletedAt)return;t.archivedAt=Date.now();t.updatedAt=Date.now();save();render();toast('완료 업무를 보관함으로 옮겼습니다.')}
function restoreArchive(id){const t=tasks.find(x=>x.id===id);if(!t)return;t.archivedAt=null;t.updatedAt=Date.now();save();render();toast('업무를 관리 중 목록으로 복원했습니다.')}
function restoreTrash(id){const t=tasks.find(x=>x.id===id);if(!t)return;t.deletedAt=null;t.updatedAt=Date.now();save();render();toast('휴지통에서 업무를 복원했습니다.')}
function purgeTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;if(!confirm(`“${t.title}” 업무를 완전히 삭제할까요? 이 작업은 되돌릴 수 없습니다.`))return;tasks=tasks.filter(x=>x.id!==id);save();render();toast('업무를 완전히 삭제했습니다.')}
function openChecklist(id){const t=tasks.find(x=>x.id===id);if(!t)return;currentChecklistTaskId=id;renderChecklistModal();els.checklistModal.classList.add('open')}
function closeChecklist(){els.checklistModal.classList.remove('open');currentChecklistTaskId=null}
function renderChecklistModal(){const t=tasks.find(x=>x.id===currentChecklistTaskId);if(!t)return;const s=checklistStats(t);$('#checklistTitle').textContent=t.title;els.checklistContent.innerHTML=`<div class="checklist-headline"><strong>세부 체크리스트</strong><span>${s.done}/${s.total} 완료 · ${s.pct}%</span></div>${s.total?`<div class="checklist-list">${t.checklistItems.map((x,i)=>`<label class="check-item ${x.done?'done':''}"><input type="checkbox" data-check-index="${i}" ${x.done?'checked':''}><span>${esc(x.text)}</span></label>`).join('')}</div>`:'<div class="empty" style="padding:28px 10px"><strong>등록된 체크리스트가 없습니다.</strong>업무 수정에서 체크리스트를 추가할 수 있습니다.</div>'}`}
function toggleChecklist(index,done){const t=tasks.find(x=>x.id===currentChecklistTaskId);if(!t||!t.checklistItems[index])return;t.checklistItems[index].done=done;t.updatedAt=Date.now();save();render();renderChecklistModal()}
function handleAction(e){const el=e.target.closest('[data-edit],[data-delete],[data-archive],[data-restore-archive],[data-restore-trash],[data-purge],[data-checklist]');if(!el)return;if(el.dataset.edit){const t=tasks.find(x=>x.id===el.dataset.edit);if(t)openModal(t)}else if(el.dataset.delete)deleteTask(el.dataset.delete);else if(el.dataset.archive)archiveTask(el.dataset.archive);else if(el.dataset.restoreArchive)restoreArchive(el.dataset.restoreArchive);else if(el.dataset.restoreTrash)restoreTrash(el.dataset.restoreTrash);else if(el.dataset.purge)purgeTask(el.dataset.purge);else if(el.dataset.checklist)openChecklist(el.dataset.checklist)}
function handleStatusChange(e){const el=e.target.closest('[data-status]');if(el)setTaskStatus(el.dataset.status,el.value)}
function duplicateSignature(t){return [t.direction,t.title,t.counterpart,t.dueDate].map(v=>String(v||'').trim().toLowerCase().replace(/\s+/g,' ')).join('|')}
function findDuplicate(t){const sig=duplicateSignature(t);return tasks.find(x=>!x.deletedAt&&duplicateSignature(x)===sig)||null}
function showImportPreview(imported){pendingImport=imported.map(task=>({task,duplicate:findDuplicate(task)}));const dup=pendingImport.filter(x=>x.duplicate).length,add=pendingImport.length-dup;els.importContent.innerHTML=`<div class="preview-summary"><div class="preview-stat"><span>읽은 업무</span><b>${pendingImport.length}</b></div><div class="preview-stat"><span>신규</span><b>${add}</b></div><div class="preview-stat"><span>중복 의심</span><b>${dup}</b></div></div><div class="preview-table-wrap"><table class="preview-table"><thead><tr><th>판정</th><th>구분</th><th>업무명</th><th>대상자</th><th>마감기한</th></tr></thead><tbody>${pendingImport.slice(0,100).map(x=>`<tr><td class="${x.duplicate?'preview-dup':'preview-new'}">${x.duplicate?'중복 의심':'신규'}</td><td>${esc(x.task.direction)}</td><td>${esc(x.task.title)}</td><td>${esc(x.task.counterpart||'-')}</td><td>${esc(x.task.dueDate)}</td></tr>`).join('')}</tbody></table></div>${pendingImport.length>100?`<div class="view-note" style="margin-top:8px">미리보기는 처음 100건까지만 표시합니다. 전체 ${pendingImport.length}건을 가져옵니다.</div>`:''}`;els.importModal.classList.add('open')}
function closeImport(){els.importModal.classList.remove('open');pendingImport=[];els.file.value=''}
function commitImport(mode){if(!pendingImport.length)return;let added=0,replaced=0,skipped=0;for(const item of pendingImport){if(item.duplicate){if(mode==='skip'){skipped++;continue}if(mode==='replace'){const old=item.duplicate,idx=tasks.findIndex(x=>x.id===old.id);tasks[idx]=normalizeTask({...item.task,id:old.id,createdAt:old.createdAt,archivedAt:old.archivedAt,deletedAt:null,checklistItems:old.checklistItems});replaced++;continue}}tasks.push(normalizeTask({...item.task,id:uid()}));added++}save();closeImport();render();toast(`엑셀 반영 완료 · 추가 ${added}건${replaced?` · 덮어쓰기 ${replaced}건`:''}${skipped?` · 중복 제외 ${skipped}건`:''}`,'success',5000)}
function downloadJson(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function backupData(){downloadJson({app:'업무터치',version:APP_VERSION,exportedAt:new Date().toISOString(),tasks,theme:document.documentElement.dataset.theme||'light',ui:{view:els.view.value,sort:els.sort.value,search:els.search.value,direction:els.direction.value,status:els.status.value,priority:els.priority.value}},`업무터치_전체백업_${localDate()}.json`);toast('업무·보관함·휴지통·설정을 전체 백업했습니다.')}
async function restoreData(file){if(!file)return;try{const data=JSON.parse(await file.text());if(data.app!=='업무터치'||!Array.isArray(data.tasks))throw new Error('업무터치 백업파일 형식이 아닙니다.');if(!confirm(`백업에 있는 ${data.tasks.length}개 업무로 현재 데이터를 복원할까요? 현재 데이터는 교체됩니다.`))return;tasks=data.tasks.map(t=>normalizeTask(t,false));purgeExpiredTrash();if(data.theme){document.documentElement.dataset.theme=data.theme;localStorage.setItem(THEME_KEY,data.theme)}if(data.ui?.view)els.view.value=data.ui.view;if(data.ui?.sort)els.sort.value=data.ui.sort;if(data.ui?.search!=null)els.search.value=data.ui.search;if(data.ui?.direction!=null)els.direction.value=data.ui.direction;if(data.ui?.status!=null)els.status.value=data.ui.status;if(data.ui?.priority!=null)els.priority.value=data.ui.priority;save();render();toast(`${tasks.length}개 업무와 설정을 백업파일에서 복원했습니다.`,'success',5000)}catch(err){toast('백업 복원 실패: '+err.message,'error',6500)}finally{els.restoreFile.value=''}}
function applyMetric(metric){els.view.value='active';els.search.value='';els.direction.value='';els.status.value='';els.priority.value='';metricMode='';if(metric==='receive')els.direction.value='인수';else if(metric==='handover')els.direction.value='인계';else if(metric==='important'){els.priority.value='높음';metricMode='important'}else if(metric==='soon')metricMode='soon';render()}
