function bind(){
 $('#addBtn').addEventListener('click',()=>openModal());$('#closeModalBtn').addEventListener('click',closeModal);$('#cancelBtn').addEventListener('click',closeModal);els.modal.addEventListener('click',e=>{if(e.target===els.modal)closeModal()});
 els.progress.addEventListener('input',()=>els.progressValue.textContent=els.progress.value+'%');els.fstatus.addEventListener('change',()=>{if(els.fstatus.value==='완료'){els.progress.value=100;els.progressValue.textContent='100%'}});
 els.form.addEventListener('submit',e=>{e.preventDefault();const existing=tasks.find(t=>t.id===els.id.value);const draft=normalizeTask({...existing,id:els.id.value||undefined,title:els.title.value,direction:els.dir.value,category:els.category.value,counterpart:els.counterpart.value,departmentRole:els.departmentRole.value,contact:els.contact.value,dueDate:els.due.value,status:els.fstatus.value,priority:els.fpriority.value,progress:els.progress.value,content:els.content.value,checklist:els.checklist.value,documents:els.documents.value,notes:els.notes.value,checklistItems:existing?.checklistItems||[]});if(!draft.title){toast('업무명을 입력해 주세요.','error');return}if(existing){const i=tasks.findIndex(t=>t.id===existing.id);tasks[i]={...draft,id:existing.id,createdAt:existing.createdAt,archivedAt:existing.archivedAt,deletedAt:existing.deletedAt};toast('업무가 수정되었습니다.')}else{tasks.unshift(draft);toast('업무가 등록되었습니다.')}save();render();closeModal()});
 [els.search,els.direction,els.status,els.priority].forEach(el=>el.addEventListener(el.tagName==='INPUT'?'input':'change',()=>{metricMode='';render()}));els.view.addEventListener('change',()=>{metricMode='';render()});els.sort.addEventListener('change',render);$('#resetFilterBtn').addEventListener('click',()=>{els.search.value='';els.direction.value='';els.status.value='';els.priority.value='';els.view.value='active';els.sort.value='due';metricMode='';render()});
 els.body.addEventListener('click',handleAction);els.mobile.addEventListener('click',handleAction);els.body.addEventListener('change',handleStatusChange);els.mobile.addEventListener('change',handleStatusChange);
 $('#templateBtn').addEventListener('click',downloadTemplate);$('#exportBtn').addEventListener('click',exportCurrent);$('#uploadBtn').addEventListener('click',()=>els.file.click());els.file.addEventListener('change',()=>uploadFile(els.file.files[0]));
 $('#backupBtn').addEventListener('click',backupData);$('#restoreBtn').addEventListener('click',()=>els.restoreFile.click());els.restoreFile.addEventListener('change',()=>restoreData(els.restoreFile.files[0]));
 $('#closeChecklistBtn').addEventListener('click',closeChecklist);$('#doneChecklistBtn').addEventListener('click',closeChecklist);els.checklistModal.addEventListener('click',e=>{if(e.target===els.checklistModal)closeChecklist()});els.checklistContent.addEventListener('change',e=>{const c=e.target.closest('[data-check-index]');if(c)toggleChecklist(Number(c.dataset.checkIndex),c.checked)});$('#editFromChecklistBtn').addEventListener('click',()=>{const t=tasks.find(x=>x.id===currentChecklistTaskId);closeChecklist();if(t)openModal(t)});
 $('#closeImportBtn').addEventListener('click',closeImport);$('#cancelImportBtn').addEventListener('click',closeImport);els.importModal.addEventListener('click',e=>{if(e.target===els.importModal)closeImport()});$('#importSkipBtn').addEventListener('click',()=>commitImport('skip'));$('#importAllBtn').addEventListener('click',()=>commitImport('all'));$('#importReplaceBtn').addEventListener('click',()=>commitImport('replace'));
 document.querySelectorAll('[data-metric]').forEach(m=>{const go=()=>applyMetric(m.dataset.metric);m.addEventListener('click',go);m.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}})});
 $('#themeBtn').addEventListener('click',()=>{const cur=document.documentElement.dataset.theme||'light',next=cur==='dark'?'light':'dark';document.documentElement.dataset.theme=next;localStorage.setItem(THEME_KEY,next);$('#themeBtn .label').textContent=next==='dark'?'라이트모드':'다크모드'});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(els.importModal.classList.contains('open'))closeImport();else if(els.checklistModal.classList.contains('open'))closeChecklist();else if(els.modal.classList.contains('open'))closeModal()}});
}
function initTheme(){const t=localStorage.getItem(THEME_KEY)||((window.matchMedia&&window.matchMedia('(prefers-color-scheme: dark)').matches)?'dark':'light');document.documentElement.dataset.theme=t;$('#themeBtn .label').textContent=t==='dark'?'라이트모드':'다크모드'}
async function runSelfTests(){const lines=[];const ok=(name,cond)=>{lines.push(`${cond?'PASS':'FAIL'} · ${name}`);if(!cond)throw new Error(name)};try{const original=JSON.parse(JSON.stringify(tasks));const ui={view:els.view.value,sort:els.sort.value};const test=normalizeTask({title:'v1.2 테스트 업무',direction:'인계',counterpart:'테스트 담당',dueDate:localDate(1),status:'진행중',priority:'높음',progress:55,content:'테스트',checklist:'첫 단계\n둘째 단계',notes:'테스트'});tasks=[...original,test];save();ok('기존 저장키 호환/업무 등록',JSON.parse(localStorage.getItem(STORAGE_KEY)).some(t=>t.title==='v1.2 테스트 업무'));ok('체크리스트 구조 변환',test.checklistItems.length===2&&!test.checklistItems[0].done);test.checklistItems[0].done=true;save();ok('체크리스트 체크 저장',JSON.parse(localStorage.getItem(STORAGE_KEY)).find(t=>t.id===test.id).checklistItems[0].done===true);const oldProgress=test.progress;setTaskStatus(test.id,'완료');ok('목록 상태 빠른 변경',tasks.find(t=>t.id===test.id).status==='완료'&&tasks.find(t=>t.id===test.id).progress===100);setTaskStatus(test.id,'진행중');ok('완료 해제 시 완료율 복원',tasks.find(t=>t.id===test.id).progress===oldProgress);archiveTask(test.id);ok('완료 업무 보관',!!tasks.find(t=>t.id===test.id).archivedAt);restoreArchive(test.id);ok('보관 해제',!tasks.find(t=>t.id===test.id).archivedAt);const t=tasks.find(x=>x.id===test.id);t.deletedAt=Date.now();ok('휴지통 이동 데이터 구조',!!t.deletedAt);restoreTrash(test.id);ok('휴지통 복원',!tasks.find(x=>x.id===test.id).deletedAt);const dup=normalizeTask({...test,id:undefined});ok('엑셀 중복 판정 키',duplicateSignature(dup)===duplicateSignature(test)&&!!findDuplicate(dup));els.view.value='active';els.sort.value='priority';ok('중요도 정렬',sortTasks([normalizeTask({...test,title:'낮음',priority:'낮음'}),normalizeTask({...test,title:'높음',priority:'높음'})])[0].priority==='높음');const backup={app:'업무터치',version:APP_VERSION,tasks};ok('백업 데이터 구조',backup.app==='업무터치'&&Array.isArray(backup.tasks));const bytes=workbookBytes(exportRows([test]));ok('엑셀 저장 생성',bytes.length>1000);const parsed=await parseXlsx(bytes.buffer);ok('엑셀 파서/재업로드',parsed[0][0]==='구분'&&rowsToTasks(parsed).length===1);ok('마감 임박 판정',isSoon(test)===true);ok('모바일 반응형 CSS','matchMedia' in window);tasks=original;els.view.value=ui.view;els.sort.value=ui.sort;save();render();lines.push('\n전체 v1.2 핵심 기능 테스트 통과');}catch(e){lines.push(`\n테스트 중단: ${e.message}`)}finally{els.search.value='';els.direction.value='';els.status.value='';els.priority.value='';metricMode='';els.tests.style.display='block';els.tests.textContent=lines.join('\n');document.body.dataset.testsDone='1';document.body.dataset.testsPassed=lines.some(x=>x.includes('전체 v1.2 핵심 기능 테스트 통과'))?'1':'0'}}
initTheme();load();bind();render();
window.__runTests=runSelfTests;
if(new URLSearchParams(location.search).get('test')==='1')setTimeout(runSelfTests,30);
