const te=new TextEncoder(),td=new TextDecoder('utf-8');
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0)}return (c^0xffffffff)>>>0}
function u16(a,o,v){a[o]=v&255;a[o+1]=(v>>>8)&255} function u32(a,o,v){u16(a,o,v&65535);u16(a,o+2,(v>>>16)&65535)}
function concat(parts){const len=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(len);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function zipStore(files){let offset=0,locals=[],centrals=[];for(const [name,content] of Object.entries(files)){const nameB=te.encode(name),data=typeof content==='string'?te.encode(content):content,crc=crc32(data);const l=new Uint8Array(30+nameB.length);u32(l,0,0x04034b50);u16(l,4,20);u16(l,6,0);u16(l,8,0);u16(l,10,0);u16(l,12,0);u32(l,14,crc);u32(l,18,data.length);u32(l,22,data.length);u16(l,26,nameB.length);u16(l,28,0);l.set(nameB,30);locals.push(l,data);const c=new Uint8Array(46+nameB.length);u32(c,0,0x02014b50);u16(c,4,20);u16(c,6,20);u16(c,8,0);u16(c,10,0);u16(c,12,0);u16(c,14,0);u32(c,16,crc);u32(c,20,data.length);u32(c,24,data.length);u16(c,28,nameB.length);u16(c,30,0);u16(c,32,0);u16(c,34,0);u16(c,36,0);u32(c,38,0);u32(c,42,offset);c.set(nameB,46);centrals.push(c);offset+=l.length+data.length}const central=concat(centrals),local=concat(locals),e=new Uint8Array(22);u32(e,0,0x06054b50);u16(e,4,0);u16(e,6,0);u16(e,8,centrals.length);u16(e,10,centrals.length);u32(e,12,central.length);u32(e,16,local.length);u16(e,20,0);return concat([local,central,e])}
function xmlEsc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c]))}
function colName(n){let s='';for(n++;n>0;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s}
function workbookBytes(rows,sheetName='인수인계작성양식'){
 const rowXml=rows.map((row,ri)=>`<row r="${ri+1}">${row.map((v,ci)=>{const ref=colName(ci)+(ri+1);if(typeof v==='number'&&Number.isFinite(v))return `<c r="${ref}" t="n"><v>${v}</v></c>`;return `<c r="${ref}" t="inlineStr"><is><t xml:space="preserve">${xmlEsc(v)}</t></is></c>`}).join('')}</row>`).join('');
 const lastCol=colName(Math.max(0,(rows[0]?.length||1)-1));
 const files={
  '[Content_Types].xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>`,
  '_rels/.rels':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>`,
  'xl/workbook.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="${xmlEsc(sheetName)}" sheetId="1" r:id="rId1"/></sheets></workbook>`,
  'xl/_rels/workbook.xml.rels':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`,
  'xl/styles.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="1"><font><sz val="11"/><name val="맑은 고딕"/></font></fonts><fills count="1"><fill><patternFill patternType="none"/></fill></fills><borders count="1"><border/></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>`,
  'xl/worksheets/sheet1.xml':`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${lastCol}${Math.max(1,rows.length)}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="10" customWidth="1"/><col min="2" max="2" width="34" customWidth="1"/><col min="3" max="3" width="18" customWidth="1"/><col min="4" max="4" width="20" customWidth="1"/><col min="5" max="6" width="22" customWidth="1"/><col min="7" max="8" width="16" customWidth="1"/><col min="9" max="9" width="15" customWidth="1"/><col min="10" max="10" width="44" customWidth="1"/><col min="11" max="11" width="42" customWidth="1"/><col min="12" max="12" width="38" customWidth="1"/></cols><sheetData>${rowXml}</sheetData></worksheet>`
 };
 return zipStore(files);
}
function downloadBlob(bytes,name){const blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),500)}
function bytesFromBase64(s){const bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function excelPriority(v){return v==='높음'?'긴급/중요':v==='낮음'?'낮음':'보통'}
function excelStatus(v){return v==='예정'?'인수/인계 대기':v}
function mergeDetailForExcel(t){return [t.content,t.notes?`[참고사항]\n${t.notes}`:''].filter(Boolean).join('\n\n')}
function exportRows(taskList){return [STANDARD_HEADERS,...taskList.map(t=>[t.direction,t.title,t.category||'',t.counterpart||'',t.departmentRole||'',t.contact||'',excelPriority(t.priority),excelStatus(t.status),t.dueDate,mergeDetailForExcel(t),t.checklist||'',t.documents||''])];}
function downloadTemplate(){const sample=[STANDARD_HEADERS,['인수','예: 사례 그룹웨어 전자결재 관리자 권한 이관','시스템/계정권한','홍길동 차장','경영지원팀 / 차장','gdhong@company.com','긴급/중요','진행중','2026-09-30','결재 문서 템플릿 수정 방법 및 관리자 OTP 전달','마스터 계정 로그인 확인, 비상 관리자 지정, 양식 백업','https://company.drive.com/manual']];downloadBlob(workbookBytes(sample),'업무터치_인수인계_엑셀등록양식.xlsx');toast('표준 12열 엑셀 등록양식을 내려받았습니다.');}
function exportCurrent(){const list=activeTasks();downloadBlob(workbookBytes(exportRows(list)),'업무터치_업무목록_'+localDate()+'.xlsx');toast(`관리 중 업무 ${list.length}건을 표준 양식으로 엑셀 저장했습니다.`);}
